#version: '3.7'
services:
  mgauth:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: mgauth
    restart: unless-stopped
    container_name: mgauth
    ports:
      - "9005:9000"
    volumes:
      - /opt/www:/opt/www
      - /tmp:/tmp/host
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo
      - .:/var/www/html
    networks:
      - mgauth-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  mgauth-network:
    driver: bridge

